# Generated by Django 3.0.8 on 2020-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTunes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='albumtitle',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artistname',
        ),
        migrations.RemoveField(
            model_name='album',
            name='releasedate',
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
