# Generated by Django 3.0.8 on 2020-07-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTunes', '0002_auto_20200715_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
